name: Extract Data and Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Download data
        run: |
          wget 
      
      - name: Install dependencies
        run: |
          pip install wheel setuptools
          pip install black==22.3.0 isort==5.10.1 flake8==4.0.1
      
      - name: Download data
        run: |
          wget -O ./data/SA_0000001439.csv "https://apps.who.int/gho/athena/api/GHO/SA_0000001439?format=csv"
