name: mortality_temporal

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  notebooks:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: pip install jupyter nbconvert nbformat
      
      - name: Launch notebook
        run:  jupyter nbconvert --to notebook --execute apps/bc_mortality_over_time.ipynb --ExecutePreprocessor.kernel_name='python3' --output ../notebook_executed

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: notebook
          path: notebook_executed.ipynb
