name: tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  notebooks:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          pip install wheel setuptools
          pip install black==22.3.0 isort==5.10.1 flake8==4.0.1
          pip install jupyter nbconvert nbformt
      
      - name: Launch notebook
        run:  jupyter nbconvert --to notebook --execute apps/breast_cancer_incidence_rate.ipynb --ExecutePreprocessor.kernel_name='python3' --output ../notebook_executed
